services:
  nobarfilm:
    container_name: nobarfilm
    image: ridhoarmand/nobarfilm:latest
    
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "--tries=1", "http://127.0.0.1:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - proxy-tier

  socket-server:
    container_name: nobarfilm-socket
    image: ridhoarmand/nobarfilm:latest
    restart: unless-stopped
    command: node dist/server/socket-server.js
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - SOCKET_PORT=4000
      - CLIENT_URL=${CLIENT_URL}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "--tries=1", "http://127.0.0.1:4000/socket.io/?EIO=4&transport=polling"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - proxy-tier

networks:
  proxy-tier:
    external: true