services:
  app:
    # Ganti 'your-username' dengan username Docker Hub kamu
    # Image ini akan otomatis ter-update jika ada push baru ke main (via Watchtower)
    image: ${DOCKER_USERNAME}/nobarfilm:latest
    container_name: nobarfilm
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - nobar-net
      - npm_network

networks:
  nobar-net:
    driver: bridge
  npm_network:
    external: true
    name: nginx-proxy-manager_default
