version: '3.8'

services:
  nobarfilm:
    container_name: nobarfilm
    # Option 1: Build from Git (Portainer method)
    image: ${DOCKER_USERNAME}/nobarfilm:latest
    # build: . # Uncomment for local build
    
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    networks:
      - nobar-net
      - npm_network

networks:
  nobar-net:
    driver: bridge
  npm_network:
    external: true
    name: nginx-proxy-manager_default
